### ISSUE TITLE
scripts to generate files for sms

### ISSUE THREAD

**Issue by papagandalf** [cambridgeltl/sw_study#2]
Hi, I am having a hard time finding the script (if there is one) that generates the file  ```en.sent.1m.5.sms```. I understand that the en.sent.1m has to go through CHIPMUNK, but ```en.sent.1m.5.sms``` is a vocabulary using the CHIPMUNK output. How can I get that? Thanks.

**Comment by zhu-y11** [comment]
Hi, you can find chipmunk [here](http://cistern.cis.lmu.de/chipmunk/). Because of its one-word-per-line input, we need to have our word level vocabulary first (*.dict and *.word in the data). You can find the script to build the word level vocabulary [here](https://github.com/cambridgeltl/sw_study/blob/master/code/word/word_input_data.py#L90-L109), or write your own script. :)
